### PR TITLE
Multiline quotes are now handled by splitting quote strings by line and rejoining them

### PR DESCRIPTION
**Pull request by ashleytowner**
This fixes the problem with multiline quotes raised in #10

### CODE REVIEW

**Comment by ashleytowner** [comment]
Sorry, it also appears my editor has supplied some formatting changes; I shall remove them.

**Comment by ashleytowner** [comment]
Should be good now

**Review by Nynir — COMMENTED** [review]
Hey @ashleytowner , were you able to get this to convert quotes within your export?

I'm not seeing that this makes any changes on my side, that being because we're already converting the quotes in the line above. That aside, even if I comment out that original `re.sub` and use the new one my sample still isn't quite converting as planned.

This is part of the sample I'm working with for reference:

`[quote]\"Text text text\"\r\n-Person who said the text [/quote]`

**Comment by ashleytowner** [comment]
Hrmm, I was able to get it to convert in my repo, but I think I might have made an error when making the PR since I don't think the original line should still be there. I'll have a look into this.

**Comment by ashleytowner** [comment]
@Nynir Sorry this took me a bit to get to, I've fixed this now. Seems to be passing my manual tests for both:

`[quote]foobar[/quote]` and `[quote]foo\nbar\n\nbaz[/quote]`.

**Pull request merged**
